### ISSUE TITLE
Crate categories

### ISSUE THREAD

**Issue by elpiel** [AeroRust/are-we-in-space-yet#7]
## Categories

The list is taken from https://github.com/AeroRust/awesome-space
With the addition of the `uom` crate instead prototype `yaiouom` for units of measure.

### List of categories

sdk - arsdk-rs
protocol - arsdk-rs, CCSDS Primary Header, BP7, DTN7
error correction - labrador-ldpc
astrodynamics - nyx
parsers - NMEA, YANP
Units of measure - uom

**Comment by Adminixtrator** [comment]
Hi @elpiel 
The crates are now available as listed in the repo. Thanks!
